# Run configuration :

# adress of SQL DTB: 
spring.datasource.url=jdbc:mysql://localhost:3306/test?serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=update

# credentials for root account :
spring.datasource.username=user
spring.datasource.password=user

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Jwt Configuration : 

oc.app.jwtSecret=openclassrooms
oc.app.jwtExpirationMs=86400000